complexity:
  LongParameterList:
    active: false
    excludes: "**/cz/vvoleman/phr/di/**"
  TooManyFunctions:
    excludes: "**/cz/vvoleman/phr/di/**"
empty-blocks:
  EmptyDefaultConstructor:
    excludes:
        - "**/cz/vvoleman/phr/feature_medicalrecord/domain/usecase/DeleteMedicalRecordUseCase.kt"
exceptions:
    TooGenericExceptionCaught:
        active: false
formatting:
  MaximumLineLength:
    active: true
    maxLineLength: 120
  NoWildcardImports:
    active: false
naming:
  FunctionParameterNaming:
    excludes:
      - "**/model/retrofit/**"
style:
  WildcardImport:
    active: false
