name: Static Analysis (Detekt)

on:
  push:
    branches:
      - main

jobs:
  detekt:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with:
          java-version: 11

      - name: Grant permission
        run: chmod +x gradlew

      - name: Run detekt
        run: ./gradlew detektAll
