name: Unit Tests (JUnit)

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          java-version: 11  # Adjust this version as needed
          distribution: 'adopt'

      - name: Build and Test
        run: |
          chmod +x ./gradlew
          ./gradlew test